### ISSUE TITLE
FabSim3 crash after successful ensemble run on localhost

### ISSUE THREAD

**Issue by djgroen** [djgroen/FabSim3#161]
Hi all. 

When I use `fabsim localhost validate_flee:mode=serial,cores=1`, the 4 instances of Flee run and complete correctly. However, after the run has concluded, FabSim3 crashes prior to the postprocessing stage with the following error:

```
Traceback (most recent call last):
  File "/home/derek/Codes/FabSim3/bin/fabric_main.py", line 767, in main
    *args, **kwargs
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/derek/Codes/FabSim3/plugins/FabFlee/FabFlee.py", line 804, in validate_flee
    flee_ensemble("validation", simulation_period, cores=1, **args)
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 171, in __call__
    return self.run(*args, **kwargs)
  File "/home/derek/.local/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/derek/Codes/FabSim3/plugins/FabFlee/FabFlee.py", line 286, in flee_ensemble
    run_ensemble(config, sweep_dir, **args)
  File "/home/derek/Codes/FabSim3/base/fab.py", line 670, in run_ensemble
    args)
  File "/home/derek/Codes/FabSim3/base/fab.py", line 563, in job
    job_info = run_stdout.split()[4]
AttributeError: 'NoneType' object has no attribute 'split'
```

I suppose FabSim3 expects something that is expected on remote machines (a stdout file) but which is not present when executing currently on localhost?

@arabnejad , could you perhaps look into this when you have time?

**Comment by djgroen** [comment]
Okay, closing this because I was using an old version by accident.
