### ISSUE TITLE
FabSim breaks in python3.12

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/FabSim3#243]
Found a bug? Please fill out the sections below. 👍

### Describe the bug

After installation, issuing any fabsim command gives the error 

ModuleNotFoundError: No module named 'imp'

For example,

fabsim localhost install_plugin:FabDummy

gives

Traceback (most recent call last):
  File "/home/arindam/FabSim3/fabsim/bin/fabsim", line 44, in <module>
    from fabsim.base import fabsim_main
  File "/home/arindam/FabSim3/fabsim/base/fabsim_main.py", line 14, in <module>
    from fabsim.base.fab import *
  File "/home/arindam/FabSim3/fabsim/base/fab.py", line 19, in <module>
    from fabsim.base.manage_remote_job import *
  File "/home/arindam/FabSim3/fabsim/base/manage_remote_job.py", line 9, in <module>
    from fabsim.base.networks import local, run
  File "/home/arindam/FabSim3/fabsim/base/networks.py", line 9, in <module>
    from fabric2 import Config, Connection
  File "/home/arindam/FabSim3/venv-testing/lib/python3.12/site-packages/fabric2/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/home/arindam/FabSim3/venv-testing/lib/python3.12/site-packages/fabric2/connection.py", line 7, in <module>
    from invoke import Context
  File "/home/arindam/FabSim3/venv-testing/lib/python3.12/site-packages/invoke/__init__.py", line 23, in <module>
    from .loader import FilesystemLoader  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arindam/FabSim3/venv-testing/lib/python3.12/site-packages/invoke/loader.py", line 3, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

### Executed steps

1. Clone the repo
2. pip3 install ruamel.yaml rich setuptools
3. fabsim localhost install_plugin:FabDummy

### Expected behavior

FabDummy should be installed

### Platform details (optional)

 - **Python version 3.12.0**

### Possible Solution (optional)

I think the package imp is removed from python 3.12.

https://discuss.python.org/t/how-do-i-migrate-from-imp/27885

People are saying to use impotlib instead... but I am not sure how easy is it to implement...

**Comment by djgroen** [comment]
Hi Arindam. This issue seems to not be a FabSim issue, but an issue with the invoke module. Have you tried upgrading it?

**Comment by arindamsaha1507** [comment]
Thanks @djgroen.

Upgrading invoke from 2.0.0 to 2.2.0 did the trick for me in Python 3.12.0.

However, I checked in my daily installation of FabSim in python 3.10.12 that invoke is in version 2.0.0 and that works.

So, is it the case that invoke is required to be in version 2.2.0 in Python 3.12 only?

How do we make it so that the correct version of invoke is installed with the correct version of Python?

BTW, I am using venv to run FabSim.

**Comment by djgroen** [comment]
Reqs updated now just to be safe :)
