### ISSUE TITLE
Typo in plugin naming "FabCannonsim"

### ISSUE THREAD

**Issue by jomichaelis** [djgroen/FabSim3#297]
The plugin **FabCannonsim** is listed as **FabCannonSim** in the `plugins.yml` file:
```yml
FabCannonSim:
  repository: https://github.com/arabnejad/FabCannonsim.git
```

Thus, the installation with `fabsim localhost install_plugin:FabCannonSim` succeeds, however subsequent calls to `fabsim` result in an error when the plugin is loaded:

```bash
...
[loading plugin] FabCannonSim ...
No module named 'plugins.FabCannonSim.FabCannonSim'
Traceback (most recent call last):
  File "/home/jo/repos/fabsim-plugins/fabsim/deploy/machines.py", line 250, in load_plugins
    plugin = importlib.import_module("plugins.{}.{}".format(key, key))
  File "/home/jo/.pyenv/versions/3.10.12/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugins.FabCannonSim.FabCannonSim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jo/repos/fabsim-plugins/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
  File "/home/jo/repos/fabsim-plugins/fabsim/base/fabsim_main.py", line 74, in main
    load_plugins()
  File "/home/jo/repos/fabsim-plugins/fabsim/deploy/machines.py", line 267, in load_plugins
    raise ImportError(e)
ImportError: No module named 'plugins.FabCannonSim.FabCannonSim'
```

This is due to the plugin's main file being called `FabCannonsim.py` and not `FabCannonSim.py`.

Fixing the typo in `plugins.yml` solves the issue and installs *FabCannonsim* under the correct directory name.

=============
The [paper](https://www.sciencedirect.com/science/article/pii/S0010465522003150) referencing FabCannonsim also uses *FabCannonsim* as name, so consistency is well preserved.

**Comment by djgroen** [comment]
I am such an amateur! ;)

Good spot and thank you for fixing this!

**Comment by jomichaelis** [comment]
Thank you for merging!
